### ISSUE TITLE
Client http proxy Support

### ISSUE THREAD

**Issue by passwa11** [luyuhuang/subsocks#2]
hey man.
thks u work ! any plan to support for the client `http proxy`? as u said,somes old soft only work well on `http proxy`.

**Comment by luyuhuang** [comment]
that's already supported. for example if you configure `listen = "127.0.0.1:10030"`, it'll accept both http requests and socks5 requests.

```
$ ./subsocks
2022/11/01 19:58:41 Using default configuration 'config.toml'
2022/11/01 19:58:41 Client starts to listen socks5://127.0.0.1:10030
2022/11/01 19:58:41 Client starts to listen http://127.0.0.1:10030
```
